version: '3.7'
services:
  bachelor-service:
    image: bachelorsapi:latest
    container_name: bachelor-service
    depends_on:
      - mongodb
    ports:
    - 8080:8080
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - 27017:27017